config {
    type: "table"
}

select
    origin as url
    ,form_factor.name as form_factor
    ,sum(first_paint.histogram.`bin`[SAFE_OFFSET(0)].density) as first_paint
    ,sum(first_contentful_paint.histogram.`bin`[SAFE_OFFSET(0)].density) as first_contentful_paint
    ,sum(largest_contentful_paint.histogram.`bin`[SAFE_OFFSET(0)].density) as largest_contentful_paint

from
    ${ref("20*")} 
where
    _table_suffix = "2511" --between "2501" and "2511"
group by all
order by 3 desc